### 1.  예외처리

- 오류가 발생했을 때 오류를 사용자에게 알려주고, 모든 데이터를 저장하게 한 후에 사용자가 프로그램을 종료할 수 있도록 하는 것이 바람직!   
- 예외: 잘못된 코드, 부정확한 데이터, 예외적인 상황에 의해 발생하는 오류
> ex) 0으로 나누는 연산, 배열의 인덱스가 한계를 넘는 경우, 디스크에서 하드웨어 오류 발생 등

```java
public class DivideByZero {
    public static void main(String[] args) {
        int result = 10 / 0;
        System.out.println("나눗셈 결과: " + result);
    }
}

// 오류
```

<br>

### 2. `try-catch` 블록
```java
try {
    // 예외가 발생할 수 있는 코드
} catch (예외 클래스 변수) {
    // 예외를 처리하는 코드
}
// 아래 구문은 생략 가능
} finally {
    // 여기 있는 코드는 try 블록이 끝나면 무조건 실행됨
}
```
<br>

- ex)   

<br>

```java
import java.util.Scanner;

public class DivideByZeroOk {
    public static void main(String[] args) {
        try {
            int retult = 10 / 0;   // 예외 발생
        } catch (ArithmeticException e) {
            System.out.println("0으로 나눌 수 없습니다.");
        }
        System.out.println("프로그램은 계속 진행됩니다.");
    }
}

// 0으로 나눌 수 없습니다.
// 프로그램은 계속 진행됩니다.
``` 

<br>

### 3.  예외의 종류

- `Error` : 너무 심각해서 할 수 있는 방법이 없음 -> 통과
- `RuntimeException` : 프로그래밍 버그이므로 스스로 고쳐야 함 -> 통과
- `Error나 RuntimeException이 아닌 예외` : 반드시 처리해야 함!! -> 검사

<br>

![exception](https://img1.daumcdn.net/thumb/R1280x0/?scode=mtistory2&fname=https%3A%2F%2Fblog.kakaocdn.net%2Fdn%2FF6qF4%2FbtrU292NxwI%2Fsq3YdvgtVWK6HNSsOBOLd1%2Fimg.png)

<br>

| 분류 | 예외 | 설명 | 
| --- | --- | --- |
| Runtime-Exception | ArithmeticException | 어떤 수를 0으로 나누는 경우 |
|| NullPointerException | NULL 객체를 참조할 때 발생하는 경우 | 
|| ClassCastException | 적절하지 못하게 클래스를 형변환 하는 경우 | 
|| NegativeArraySizeException | 배열의 크기가 음수값인 경우 | 
|| OutOfMemoryException | 사용 가능한 메모리가 없는 경우 |
|| NoClassDefFoundException | 원하는 클래스를 찾지 못한 경우 | 
|| ArrayIndexOutOfBoundsException | 배열을 참조하는 인덱스가 잘못된 경우 |

<br>

| 분류 | 예외 | 설명 |
| --- | --- | --- |
| Checked-Exception | ClassNotFoundException | 클래스가 발견되지 않을 때 |
|| IOException | 입출력 오류 | 
|| illegalAccessException | 클래스의 접근이 금지되었을 때 |
|| NoSuchMethodException | 메소드가 발견되지 않을 때 |
|| NoSuchFieldException | 필드가 발견되지 않을 때 |
|| InterruptedException | 스레드가 다른 스레드에 의해 중단되었을 때 |
|| FileNotFoundException | 파일을 찾지 못했을 때 |

<br>

```java
// 배열 인덱스 예외 처리

public class ArrayError {
    public static void main(String[] args) {
        int [] array = { 1, 2, 3, 4, 5 };
        int i = 0;
        
        try  {
            for (i = 0; i <= array.length; i++)
                System.out.print(array[i] + " ");
        } catch ArrayIndexOutOfBoundsException e) {
            System.out.pritnln("인덱스 " + i + "는 사용할 수 없네요!");
        }
    }
}

// 1 2 3 4 5 인덱스 5는 사용할 수 없네요!
```

<br>

```java
// 입력 예외 처리

public class ExceptionTest3 {
    public static void main(String[] args) {
        try { 
            int num = Integer.parseInt("ABC");
            System.out.println(num);
        } catch (NumberFormatException e) {
            System.out.println("NumberFormat 예외 발생");
        }
    }
}
```

<br>

### 4.  `try - with - resources` 문장

- 문장의 끝에서 리소스들이 자동으로 닫혀지게 함   
```java
import java.io.*;

public class TryTest {
    public static void main(String[] args) {
        try (FileReader fr = new FileReader("test.txt")) {
            char[] a = new char[50];
            fr.read(a);
            for (char c : a)
                System.out.print(c);
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
}
```  

<br>

### 5.  예외 떠넘기기

- 가끔 메소드가 발생되는 예외를 그 자리에서 처리하지 않고, 자신을 호출한 __상위 메소드로__ 전달하는 편이 더 적절할 수 있음   

<br>

```java
import java.io.*;

pulbic class ExceptionTest {
    public static void main(String[] args) throws IOException {
        FileReader fr = new FileReader("test.txt");
        char[] a = new char[50];
        fr.read(a);
        for (char c : a)
            System.out.print(c);
    }
}
```